"""add expires_at to invite_codes

Revision ID: da3b0f22e094
Revises: aba3964e0fef
Create Date: 2026-04-01 12:13:49.913152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3b0f22e094'
down_revision: Union[str, None] = 'aba3964e0fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
